### ISSUE TITLE
Evaluate compatibility with Python 3.1, 3.2

### ISSUE THREAD

**Issue by srishanbhattarai** [srishanbhattarai/Harbor-CLI#45]
* Check if the app runs under Python 3.1 and 3.2. 
* Travis experiencing  [issues](https://github.com/travis-ci/travis-ci/issues/2312) with 3.0 - 3.2 downloads so a local `tox` check would *probably* be the way to go. (maybe Travis can be given a Linux distro and it'll work fine?)
* If the tests do pass under these versions -
  * Update classifiers under `setup.py`
  * Update Python version numbers for Travis

**Comment by hugovk** [comment]
Do you really need Python 3.1 and 3.2? 

They're both EOL and I think you'll have a hard time being able to test them. Here's reasons against 3.2:

* Unsupported since [2016-02-27](https://en.wikipedia.org/wiki/CPython#Version_history)
* pip 8 no longer supports Python 3.2 ([link](https://pip.pypa.io/en/stable/news/))
* Coverage 4 no longer supports Python 3.2 ([link](https://bitbucket.org/ned/coveragepy/issues/407/coverage-failing-on-python-325-using))
* Virtually no PyPI traffic (June 2016) https://github.com/pypa/pip/issues/3796
* It's a pain to deal with its odd Unicode handling

The same and more will apply for 3.1. 

They have very few users and for good reason. Here are the pip downloads from PyPI for the last month:
```
$ pypinfo --percent --pip "" pyversion
python_version percent download_count
-------------- ------- --------------
2.7              77.1%    496,306,375
3.6               9.5%     61,145,821
3.5               7.8%     50,500,267
3.4               4.1%     26,675,278
2.6               1.2%      8,001,549
3.3               0.1%        767,668
3.7               0.1%        388,856
3.2               0.0%         49,881
None              0.0%         21,666
2.8               0.0%            203
3.1               0.0%            131
```

In fact, 3.3 is also now EOL and is seeing support dropped from many packages.

**Comment by srishanbhattarai** [comment]
It's not that I *need* them. Unaware of these statistics, I figured they would be nice to have. Thank you for your detailed argument against supporting 3.1 and 3.2. I'll probably close this soon. 👍 😃
